// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6tASELRAwP48xaBoUBhxwcl_AtkDoBI',
    appId: '1:738981562226:web:22c108eb52e0512704bfeb',
    messagingSenderId: '738981562226',
    projectId: 'room-design-app-9ba79',
    authDomain: 'room-design-app-9ba79.firebaseapp.com',
    storageBucket: 'room-design-app-9ba79.firebasestorage.app',
    measurementId: 'G-WJ8GC4PV1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9cP3GEJoZU8Jy2YOTXRYTrh7wZ6FivE',
    appId: '1:738981562226:android:f76d79196dede30a04bfeb',
    messagingSenderId: '738981562226',
    projectId: 'room-design-app-9ba79',
    storageBucket: 'room-design-app-9ba79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDh-xNg8tnt8iEDrsj-DzCrx0W9rhvOc',
    appId: '1:738981562226:ios:e51bbc4fc7cdcd3e04bfeb',
    messagingSenderId: '738981562226',
    projectId: 'room-design-app-9ba79',
    storageBucket: 'room-design-app-9ba79.firebasestorage.app',
    iosClientId: '738981562226-gmou0k062nt67e3s65nc66tfgj0t0dbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomstyler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATDh-xNg8tnt8iEDrsj-DzCrx0W9rhvOc',
    appId: '1:738981562226:ios:e51bbc4fc7cdcd3e04bfeb',
    messagingSenderId: '738981562226',
    projectId: 'room-design-app-9ba79',
    storageBucket: 'room-design-app-9ba79.firebasestorage.app',
    iosClientId: '738981562226-gmou0k062nt67e3s65nc66tfgj0t0dbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomstyler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw6tASELRAwP48xaBoUBhxwcl_AtkDoBI',
    appId: '1:738981562226:web:c7c394944c7aa56504bfeb',
    messagingSenderId: '738981562226',
    projectId: 'room-design-app-9ba79',
    authDomain: 'room-design-app-9ba79.firebaseapp.com',
    storageBucket: 'room-design-app-9ba79.firebasestorage.app',
    measurementId: 'G-FCPKXYY04Y',
  );

}